name: Publish VS Code Extension

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install vsce
        run: npm install -g vsce

      - name: Package extension
        run: vsce package --no-dependencies

      - name: Publish to Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          vsce publish patch || vsce publish --packagePath $(ls *.vsix | head -n1)